function [deda] = Downwash_on_Tail(AR,b,taper,Lh)

% Brian Roth
% ENGR 475 - Mechanics of Flight
% May 4, 2021
%
% Goal: The wing induces a downwash angle on the horizontal tail, reducing 
%   its effectiveness. In this function, we create an equation to predict 
%   the derivative of downwash angle (epsilon) w.r.t. angle of attack.
%
% Reference:
%   Yahyaoui, Mondher, A New Method for the Prediction of the Downwash 
%       Angle Gradient, International Journal of Aviation, Aeronautics, 
%       and Aerospace, Volume 6, Issue 3, Article 9, 2019. 
%   Note: All data was drawn from Table 2 of this paper. The data was
%   generated by VLM and validated by experimental data originally
%   published by Roskam.
%
% Approach:
%   Curve fit data from Yahyaoui to create a 2-D quadratic equation for 
%   d_epsilon / d_alpha as a function of the wing's aspect and taper ratios.
%
% Model:
%   de/da = (1 + z*c1) / (c2 + z*c3),
%       where z = L / (b/2)
%             L = distance from c/4 of wing to c/4 of tail
%             b = wing span
%       For example, if the distance from wing to tail is b/2, then z = 1.

% Step #1 - Take 20 data points from Yahyaoui and use them to define an
% over-determined system of equations. The system of equations must be
% solved for three different r.h.s. vectors (b1, b2, and b3) in order to
% solve for the three coefficients (c1, c2, and c3) of the model.

% Equations (with b1. To compute c2 and c3, simply swap in b2 or b3.)
%    b = a0 + a1*AR + a2*taper + a3*AR^2 + a4*taper^2 + a5*AR*taper
%
% 2.73 = a0 + a1*4 + a2*1.0 + a3*(4)^2 + a4*(1.0)^2 + a5*(4)*(1.0)	
% 2.42 = a0 + a1*5 + a2*1.0 + a3*(5)^2 + a4*(1.0)^2 + a5*(5)*(1.0)	
% 2.38 = a0 + a1*6 + a2*1.0 + a3*(6)^2 + a4*(1.0)^2 + a5*(6)*(1.0)	
% 2.48 = a0 + a1*7 + a2*1.0 + a3*(7)^2 + a4*(1.0)^2 + a5*(7)*(1.0)	
% 2.59 = a0 + a1*8 + a2*1.0 + a3*(8)^2 + a4*(1.0)^2 + a5*(8)*(1.0)	
% 	
% 2.44 = a0 + a1*4 + a2*0.8 + a3*(4)^2 + a4*(0.8)^2 + a5*(4)*(0.8)	
% 2.04 = a0 + a1*5 + a2*0.8 + a3*(5)^2 + a4*(0.8)^2 + a5*(5)*(0.8)	
% 1.91 = a0 + a1*6 + a2*0.8 + a3*(6)^2 + a4*(0.8)^2 + a5*(6)*(0.8)	
% 1.88 = a0 + a1*7 + a2*0.8 + a3*(7)^2 + a4*(0.8)^2 + a5*(7)*(0.8)	
% 1.90 = a0 + a1*8 + a2*0.8 + a3*(8)^2 + a4*(0.8)^2 + a5*(8)*(0.8)	
% 	
% 2.35 = a0 + a1*4 + a2*0.7 + a3*(4)^2 + a4*(0.7)^2 + a5*(4)*(0.7)	
% 2.03 = a0 + a1*5 + a2*0.7 + a3*(5)^2 + a4*(0.7)^2 + a5*(5)*(0.7)	
% 1.72 = a0 + a1*6 + a2*0.7 + a3*(6)^2 + a4*(0.7)^2 + a5*(6)*(0.7)	
% 1.89 = a0 + a1*7 + a2*0.7 + a3*(7)^2 + a4*(0.7)^2 + a5*(7)*(0.7)	
% 1.67 = a0 + a1*8 + a2*0.7 + a3*(8)^2 + a4*(0.7)^2 + a5*(8)*(0.7)	
% 	
% 2.50 = a0 + a1*4 + a2*0.6 + a3*(4)^2 + a4*(0.6)^2 + a5*(4)*(0.6)	
% 1.88 = a0 + a1*5 + a2*0.6 + a3*(5)^2 + a4*(0.6)^2 + a5*(5)*(0.6)	
% 1.73 = a0 + a1*6 + a2*0.6 + a3*(6)^2 + a4*(0.6)^2 + a5*(6)*(0.6)	
% 1.65 = a0 + a1*7 + a2*0.6 + a3*(7)^2 + a4*(0.6)^2 + a5*(7)*(0.6)	
% 1.60 = a0 + a1*8 + a2*0.6 + a3*(8)^2 + a4*(0.6)^2 + a5*(8)*(0.6)	

% Step #2 - Solve system of equations
b1 = [2.73; 2.42; 2.38; 2.48; 2.59; 2.44; 2.04; 1.91; 1.88; 1.90;
      2.35; 2.03; 1.72;       1.67; 2.50; 1.88; 1.73; 1.65; 1.60];
b2 = [-0.30; -0.12; -0.08; -0.16; -0.28; -0.17; 0.09; 0.21; 0.27; 0.29;
      -0.14;  0.09;  0.34;         0.46; -0.23; 0.16; 0.30; 0.39; 0.48];
b3 = [7.38; 7.81; 8.89; 10.53; 12.30; 6.39; 6.34; 6.89; 7.70; 8.70;
      6.03; 6.14; 6.00;         7.47; 6.23; 5.57; 5.92; 6.39; 6.93];

A = [1 4 1.0 16 1.00 4.0; 1 5 1.0 25 1.00 5.0; 1 6 1.0 36 1.00 6.0; 1 7 1.0 49 1.00 7.0; 1 8 1.0 64 1.00 8.0;
     1 4 0.8 16 0.64 3.2; 1 5 0.8 25 0.64 4.0; 1 6 0.8 36 0.64 4.8; 1 7 0.8 49 0.64 5.6; 1 8 0.8 64 0.64 6.4;
     1 4 0.7 16 0.49 2.8; 1 5 0.7 25 0.49 3.5; 1 6 0.7 36 0.49 4.2;                      1 8 0.7 64 0.49 5.6;
     1 4 0.6 16 0.36 2.4; 1 5 0.6 25 0.36 3.0; 1 6 0.6 36 0.36 3.6; 1 7 0.6 49 0.36 4.2; 1 8 0.6 64 0.36 4.8];

c1 = A\b1;
c2 = A\b2;
c3 = A\b3;
% Solving yields the following equations, where the coefficients are
% defined by c1, c2, and c3:
%    C1 = 8.8327 - 1.3530*AR - 7.9844*taper + 0.0721*AR^2 + 4.2823*taper^2 + 0.4619*AR*taper
%    C2 = -5.2076 + 0.9611*AR + 6.7122*taper - 0.0436*AR^2 - 3.2369*taper^2 - 0.428*AR*taper
%    C3 = 25.6304 - 3.6458*AR - 32.7624*taper + 0.1827*AR^2 + 15.5067*taper^2 + 2.6575*AR*taper

% Step #3 - Solve for de/da
z = Lh/(b/2); 

C1 = c1(1) + c1(2)*AR + c1(3)*taper + c1(4)*AR^2 + c1(5)*taper^2 + c1(6)*AR*taper;
C2 = c2(1) + c2(2)*AR + c2(3)*taper + c2(4)*AR^2 + c2(5)*taper^2 + c2(6)*AR*taper;
C3 = c3(1) + c3(2)*AR + c3(3)*taper + c3(4)*AR^2 + c3(5)*taper^2 + c3(6)*AR*taper;
deda = (1+z*C1) / (C2+z*C3);